### ISSUE TITLE
Have a bugzilla query link instead of a buglist

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugdash#10]
The bug icon on each list calls bugzilla with a list of bug numbers. It would be nicer to have a query (where possible) such that one can tweak the query further if needed.

**Comment by globau** [comment]
This is a conscious decision to avoid encouragement of further fragmentation the rules around triage.  It also, as you mentioned, isn't always possible due to post-processing of the search results.  For both of these reasons I went with "not at all" rather than "sometimes".

If you have suggestions for tweaks that improve the queries (triage or otherwise) you're welcome to file issues and/or start a discussion.

**Comment by jensstutte** [comment]
No further discussion needed, thanks.
