### ISSUE TITLE
Exclude wontfix bugs from the Carry-Over Burndown lists

### ISSUE THREAD

**Issue by DonalMe** [mozilla/bugdash#16]
Burndown List queries in https://bugdash.moz.tools/#tab.reo should not list bugs If the version is set to wontfix.

Example: 
`114 (Beta) Carry Over Bugs With NEEDINFO` lists https://bugzilla.mozilla.org/show_bug.cgi?id=1832351 but Firefox114 is set to `wontfix` in that bug.

The query should only return bugs where the version status is `affected` or `fix-optional`.

**Comment by globau** [comment]
[The query](https://bugzilla.mozilla.org/query.cgi?classification=Client%20Software&classification=Components&classification=Developer%20Infrastructure&classification=Other&classification=Server%20Software&f1=cf_status_firefox114&f10=keywords&f11=OP&f12=CP&f2=OP&f3=cf_status_firefox113&f4=cf_status_firefox113&f5=cf_status_firefox113&f6=CP&f7=flagtypes.name&f8=cf_tracking_firefox114&f9=product&include_fields=assigned_to%2Ccomponent%2Ccreation_time%2Ccreator%2Cflags%2Cgroups%2Cid%2Ckeywords%2Clast_change_time%2Cpriority%2Cproduct%2Cseverity%2Csummary%2Ctriage_owner%2Ctype&j11=OR&j2=OR&keywords=regression&keywords_type=allwords&limit=0&list_id=16559688&n2=1&o1=equals&o10=nowordssubstr&o3=equals&o4=equals&o5=equals&o7=notsubstring&o8=notequals&o9=notequals&query_format=advanced&resolution=---&v1=affected&v10=stalled%2Cintermittent-failure&v3=unaffected&v4=%3F&v5=---&v7=needinfo&v8=-&v9=Testing) currently only lists bugs where the relevant `status-firefox` flag is set to `affected`.

Right now https://bugzilla.mozilla.org/show_bug.cgi?id=1832351 isn't listed in either of the 114 carry-over lists.

That bug had `status-firefox114: affected` up until recently when it was changed to `wontfix`, perhaps BugDash's list was generated before the bug was updated?

**Comment by DonalMe** [comment]
Sorry for the noise, must have been bad timing when looking at the list just as the status was changed.
