### ISSUE TITLE
Stop ignoring defects filed by the WPT-Sync bot

### ISSUE THREAD

**Issue by globau** [mozilla/bugdash#33]
In issue #32 @saschanaz asked for the WPT dashboard to be merged into bugdash.  With bugdash's focus on Bugzilla and the WPT dashboard's broader scope this isn't going to happen.

However, it appears the actual requirement of #32 is to ensure that WPT issues are triaged appropriately, which I'm in full support of.

Currently bugdash ignores bugs filed by wptsync in the following lists:
- triage-needed
- recent-enhancements
- recent-tasks
- long-defects
- long-tasks
- long-enhancements

The only reason these exclusions are in place is because they were part of [the tool bugdash replaced](https://github.com/mozilla/triage-center/commit/bc49d2e5d4a58acbd71b5e0178deee4e6cb99589).

I propose removing the wptsync exclusion from the following lists only (both of which deal with defects only):
- triage-needed
- long-defects

@jgraham can you think of any reason for the initial exclusion of wptsync defects from a triage dashboard?

**Comment by jgraham** [comment]
wptsync files two kinds of bugs: one that tracks the sync of upstream PRs, and one for tracking failures that might represent important actionable issues.

I don't think the former should be included in any dashboard. They are filed as P4 which I believe is otherwise unused.

The latter are much more suitable for triage, and I think they could be included. However I also expect this to prompt more desire for changes on the wpt sync side to ensure the bugs are maximally actionable.

**Comment by globau** [comment]
Thanks @jgraham.  As the PR tracking bugs are `tasks` we don't need to take the priority into account (triage-needed is only for defects)
